version: 2
models:
  - name: stg_bookings
    description: Staging model for bookings
    columns:
      - name: booking_id
        description: Unique identifier for the booking
        tests:
          - not_null
      - name: booking_date
        description: Date the booking was made
        tests:
          - not_null
      - name: customer_id
        description: Unique identifier for the customer
        tests:
          - not_null
      - name: number_of_passengers
        description: Number of passengers in the booking
        tests:
          - not_null
  - name: stg_passengers
    description: Staging model for passengers
    columns:
      - name: passenger_id
        description: Unique identifier for the passenger
        tests:
          - not_null
      - name: first_name
        description: Passenger's first name
        tests:
          - not_null
      - name: last_name
        description: Passenger's last name
        tests:
          - not_null
      - name: date_of_birth
        description: Passenger's date of birth
        tests:
          - not_null
  - name: stg_segments
    description: Staging model for segments
    columns:
      - name: segment_id
        description: Unique identifier for the segment
        tests:
          - not_null
      - name: origin
        description: Departure airport code
        tests:
          - not_null
      - name: destination
        description: Arrival airport code
        tests:
          - not_null
      - name: departure_datetime
        description: Scheduled departure date and time
        tests:
          - not_null
      - name: arrival_datetime
        description: Scheduled arrival date and time
        tests:
          - not_null
      - name: airline_code
        description: Airline code for the segment
        tests:
          - not_null
      - name: flight_number
        description: Flight number for the segment
        tests:
          - not_null
  - name: stg_tickets
    description: Staging model for tickets
    columns:
      - name: ticket_id
        description: Unique identifier for the ticket
        tests:
          - not_null
      - name: booking_id
        description: Unique identifier for the booking
        tests:
          - not_null
      - name: issue_date
        description: Date the ticket was issued
        tests:
          - not_null
      - name: ticket_price
        description: Price of the ticket
        tests:
          - not_null
  - name: stg_ticketPassenger
    description: Staging model for ticketPassenger
    columns:
      - name: ticket_id
        description: Unique identifier for the ticket
        tests:
          - not_null
      - name: passenger_id
        description: Unique identifier for the passenger
        tests:
          - not_null
  - name: stg_ticketSegment
    description: Staging model for ticketSegment
    columns:
      - name: ticket_id
        description: Unique identifier for the ticket
        tests:
          - not_null
      - name: segment_id
        description: Unique identifier for the segment
        tests:
          - not_null
